### ISSUE TITLE
Bug: Initiative tracker returns error message on Chrome after deleting combatants from combat

### ISSUE THREAD

**Issue by aryehh** [jbarzilai/5e-monsters#28]
Hi, this is a recent error that I've noticed. I'm using the initiative tracker on Chrome, and as far as I can tell, it seems to run fine, if a bit slowly, until I delete a combatant from the current combat, at which point it seems to crash and return the "aw, snap!" error message in Chrome. I'm not sure if this is an issue with the browser that I'm using interfacing with the tracker or a bug with the tracker itself. Help would be appreciated.

**Comment by jbarzilai** [comment]
Hi, thanks for the bug report. Could you please report this on the main fork, https://github.com/Asmor/5e-monsters ? Thanks. I don't do any development on this branch any longer.
